name: Run tests

on: 
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'


      - name: Install deps
        run: yarn

      - run: yarn build
      - run: yarn test